### ISSUE TITLE
Oops: 96000004 [#1] PREEMPT SMP in multithread

### ISSUE THREAD

**Issue by helloearth012** [cameron314/readerwriterqueue#84] opened 2020-05-12 17:47 UTC
```
The full error message is 
Unable to handle kernel paging request at virtual address 19e5df4992b9e0
pgd = ffffffc04e352000
[19e5df4992b9e0] *pgd=0000000000000000
*pud=0000000000000000

Internal error: Oops: 96000004 [#1] PREEMPT SMP
Modules linked in:  driver A
CPU: 2 PID: 785 Comm: POSIX timer 1 Tainted: G        W       4.9.27 #1
```

When I run with single thread, everything is good, but when I run with multi-thread, will encounter error above randomly. Does anyone encountered this same issue?

Below is my peosdu code.

single thread
```
moodycamel::BlockingReaderWriterQueue<int> q_empty;
moodycamel::BlockingReaderWriterQueue<int> q_result;

for(int i = 0; i < 3; i++){
    q_empty.enqueue(i);        
}

while(1){
	q_empty.wait_dequeue(idx_writer);
	//write data in buffer[idx_writer], data is processed with driver A
	q_result.enqueue(idx_writer);

	q_result.wait_dequeue(idx_reader);
	//read data in buffer[idx_reader], then release this idx to available empty queue
	q_empty.enqueue(idx_reader);
}
```

 multi-thread
```
moodycamel::BlockingReaderWriterQueue<int> q_empty;
moodycamel::BlockingReaderWriterQueue<int> q_result;

for(int i = 0; i < 3; i++){
    q_empty.enqueue(i);        
}

thread_writer(){
	while(1){
		q_empty.wait_dequeue(idx_writer);
		//write data in buffer[idx_writer], data is processed with driver A
		q_result.enqueue(idx_writer);	
	}	
}

thread_reader(){
	while(1){
		q_result.wait_dequeue(idx_reader);
		//read data in buffer[idx_reader], then release this idx to available empty queue
		q_empty.enqueue(idx_reader);
	}
}
```

**Comment by cameron314** [comment] 2020-05-12 17:57
It looks like you're trying to use the queue from within a kernel space driver. This is not supported. See https://stackoverflow.com/a/17463308

**Comment by helloearth012** [comment] 2020-05-12 18:45
No,it's used in pure user space. 

//write data in buffer[idx], data is processed with driver A
Only here, after q_empty.wait_dequeue(idx_writer), here this buffer[idx_writter] information will pass to driver through driver's user space API. But the readerwriterqueue is totally used in user space.

**Comment by helloearth012** [comment] 2020-05-14 05:21
@cameron314  Thank you so much for your reply previously, I know you multi-producer multi-consumer version is verified by many people and even with benchmark.  Can I know if this single producer and single consumer is verified intensively? Thanks again.

**Comment by cameron314** [comment] 2020-05-14 11:26
It's tested pretty thoroughly, and it's a lot simpler than the MPMC one. There's of course the possibility of a bug, but this is the first time I see a segfault with this queue as far as I can remember.

If you use the plain ReaderWriterQueue instead of the blocking one, can you still reproduce?

**Comment by helloearth012** [comment] 2020-05-14 13:31
Tried plain ReaderWriterQueue, same issue after running some time.
The weird thing is no matter plain queue or blocking queue, single thread version works perfectly, this error only happens in multi-thread.  In multi-thread, it does crashes at the first time in the loop, it could run a few hundred times in the loop, sometimes longer, sometimes shorter.

**Comment by cameron314** [comment] 2020-05-14 14:34
Hmm ok. Does your multi-thread code reproduce the bug in isolation? Or only when integrated into the rest of your code?

**Comment by cameron314** [comment] 2020-05-16 17:02
Can you log the index just before the crash?

**Comment by cameron314** [comment] 2020-09-25 17:23
Closing for now. Please reopen if you find an example to reproduce.

**Closed by cameron314** 2020-09-25 17:23 UTC
